// Facts.jsx
const Facts = [
  "The Earth is approximately 4.54 billion years old.",
  "A group of flamingos is called a 'flamboyance.'",
  "The Great Wall of China is visible from space with the naked eye.",
  "Bananas are berries, but strawberries aren't.",
  "A day on Venus is longer than a year on Venus.",
  "Honey never spoils; archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
  "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion.",
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896, lasting only 38 minutes.",
  "Octopuses have three hearts and blue blood.",
  "Cows have best friends and can become stressed when they are separated.",
  "The average person spends six months of their life waiting for red lights to turn green.",
  "A single cloud can weigh more than 1 million pounds.",
  "The longest time between two twins being born is 87 days.",
  "The world's largest desert is Antarctica.",
  "Honey never spoils; sealed pots found in ancient Egyptian tombs thousands of years old are still safe to eat.",
  "A jiffy is an actual unit of time: 1/100th of a second.",
  "The human brain is more active during sleep than during the day when awake.",
  "The first computer programmer was a woman named Ada Lovelace.",
  "Honeybees can recognize human faces.",
  "The shortest war in history was between Britain and Zanzibar in 1896, lasting only 38 minutes.",
  "An octopus has three hearts.",
  "The Great Wall of China is not visible from the Moon without aid.",
  "A group of pugs is called a 'grumble.'",
  "A day on Venus is longer than a year on Venus.",
  "The Hawaiian alphabet only has 13 letters.",
  "The only mammal capable of flight is the bat.",
  "A single rainforest can produce 20% of the Earth's oxygen.",
  "Cows have best friends.",
  "Bananas are berries, but strawberries aren't.",
  "The world's largest volcano is underwater in Hawaii.",
  "A giraffe's tongue can be up to 45 centimeters long.",
  "Penguins can jump up to 6 feet in the air.",
  "The shortest war in history was between Britain and Zanzibar in 1896, lasting only 38 minutes.",
  "A bolt of lightning is five times hotter than the surface of the sun.",
  "The oldest known vegetable is the pea.",
  "Polar bear skin is black.",
  "A flea can jump 350 times its body length.",
  "The Mona Lisa has no eyebrows.",
  "The average person will spend six months of their life waiting for red lights to turn green.",
  "The word 'nerd' was first coined by Dr. Seuss in 'If I Ran the Zoo.'",
  "The first known contraceptive was crocodile dung used by Egyptians in 2000 BC.",
  "A group of flamingos is called a 'flamboyance.'",
  "There are more possible iterations of a game of chess than there are atoms in the known universe.",
  "An individual blood cell takes about 60 seconds to make a complete circuit of the body.",
  "Squirrels plant thousands of new trees each year simply by forgetting where they put their acorns.",
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896, lasting only 38 minutes.",
  "Venus is the only planet that rotates clockwise.",
  "A day on Venus is longer than a year on Venus.",
  "The Great Wall of China is visible from space with the naked eye.",
  "Bananas are berries, but strawberries aren't.",
  "A 'jiffy' is an actual unit of time: 1/100th of a second.",
  "Honey never spoils; archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
  "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion.",
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896, lasting only 38 minutes.",
  "Octopuses have three hearts and blue blood.",
  "Cows have best friends and can become stressed when they are separated.",
  "A cat has 32 muscles in each ear.",
  "The average person walks the equivalent of three times around the world in a lifetime.",
  "A single rainforest can produce 20% of the Earth's oxygen.",
  "A group of owls is called a 'parliament.'",
  "The longest recorded flight of a chicken is 13 seconds.",
  "The dot over the letter 'i' is called a tittle.",
  "There are more possible iterations of a game of chess than there are atoms in the known universe.",
  "A 'billion' seconds is about 31.7 years.",
  "The shortest war in history was between Britain and Zanzibar in 1896, lasting only 38 minutes.",
  "The human brain is more active during sleep than during the day when awake.",
  "A group of jellyfish is called a 'smack.'",
  "A day on Venus is longer than a year on Venus.",
  "The Great Wall of China is not visible from the Moon without aid.",
  "A 'jiffy' is an actual unit of time: 1/100th of a second.",
  "The word 'nerd' was first coined by Dr. Seuss in 'If I Ran the Zoo.'",
  "A snowflake can take up to two hours to fall from the cloud to the ground.",
  "The shortest war in history was between Britain and Zanzibar in 1896, lasting only 38 minutes.",
  "A bolt of lightning is five times hotter than the surface of the sun.",
  "The oldest known vegetable is the pea.",
  "Polar bear skin is black.",
  "A flea can jump 350 times its body length.",
  "The Mona Lisa has no eyebrows.",
  "The average person will spend six months of their life waiting for red lights to turn green.",
  "The word 'nerd' was first coined by Dr. Seuss in 'If I Ran the Zoo.'",
  "The first known contraceptive was crocodile dung used by Egyptians in 2000 BC.",
  "A group of flamingos is called a 'flamboyance.'",
  "There are more possible iterations of a game of chess than there are atoms in the known universe.",
  "An individual blood cell takes about 60 seconds to make a complete circuit of the body.",
  "Squirrels plant thousands of new trees each year simply by forgetting where they put their acorns.",
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896, lasting only 38 minutes.",
  "Venus is the only planet that rotates clockwise.",
  "A day on Venus is longer than a year on Venus.",
  "The Great Wall of China is visible from space with the naked eye.",
  "Bananas are berries, but strawberries aren't.",
  "A 'jiffy' is an actual unit of time: 1/100th of a second.",
  "Honey never spoils; archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
  "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion.",
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896, lasting only 38 minutes.",
  "Octopuses have three hearts and blue blood.",
  "Cows have best friends and can become stressed when they are separated.",
  "The largest desert in the world is Antarctica.",
  "A 'jiffy' is an actual unit of time: 1/100th of a second.",
  "A group of pugs is called a 'grumble.'",
  "The human brain has a memory capacity equivalent to approximately 2.5 petabytes.",
  "Cows have best friends and can become stressed when they are separated.",
  "A baby spider is called a spiderling.",
  "The world's largest volcano is underwater in Hawaii.",
  "The longest word without a vowel is 'rhythms.'",
  "The average person will spend six months of their life waiting for red lights to turn green.",
  "A day on Venus is longer than a year on Venus.",
  "A 'quokka' is a small herbivorous marsupial that is often referred to as the 'happiest animal on Earth.'",
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896, lasting only 38 minutes.",
  "The longest word in the English language without a vowel is 'rhythms.'",
  "The word 'bookkeeper' (and its variants) is the only unhyphenated English word with three consecutive double letters.",
  "A 'googol' is the number 1 followed by 100 zeros.",
  "Bananas are berries, but strawberries aren't.",
  "Honey never spoils; archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
  "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion.",
  "Octopuses have three hearts and blue blood.",
  "A group of flamingos is called a 'flamboyance.'",
  "A single cloud can weigh more than 1 million pounds.",
  "The shortest war in history was between Britain and Zanzibar in 1896, lasting only 38 minutes.",
  "A single rainforest can produce 20% of the Earth's oxygen.",
  "A 'billion' seconds is about 31.7 years.",
  "The word 'nerd' was first coined by Dr. Seuss in 'If I Ran the Zoo.'",
  "The average person walks the equivalent of three times around the world in a lifetime.",
  "A group of owls is called a 'parliament.'",
  "The longest recorded flight of a chicken is 13 seconds.",
  "The dot over the letter 'i' is called a tittle.",
  "There are more possible iterations of a game of chess than there are atoms in the known universe.",
  "A 'billion' seconds is about 31.7 years.",
  "The longest recorded flight of a chicken is 13 seconds.",
  "The dot over the letter 'i' is called a tittle.",
  "The world's largest desert is Antarctica.",
  "A group of owls is called a 'parliament.'",
  "The longest recorded flight of a chicken is 13 seconds.",
  "The dot over the letter 'i' is called a tittle.",
  "The average person walks the equivalent of three times around the world in a lifetime.",
  "A 'jiffy' is an actual unit of time: 1/100th of a second.",
  "The human brain is more active during sleep than during the day when awake.",
  "A group of jellyfish is called a 'smack.'",
  "A day on Venus is longer than a year on Venus.",
  "The Great Wall of China is not visible from the Moon without aid.",
  "A 'jiffy' is an actual unit of time: 1/100th of a second.",
  "The word 'nerd' was first coined by Dr. Seuss in 'If I Ran the Zoo.'",
  "A snowflake can take up to two hours to fall from the cloud to the ground.",
  "The shortest war in history was between Britain and Zanzibar in 1896, lasting only 38 minutes.",
  "A bolt of lightning is five times hotter than the surface of the sun.",
  "The oldest known vegetable is the pea.",
  "Polar bear skin is black.",
  "A flea can jump 350 times its body length.",
  "The Mona Lisa has no eyebrows.",
  "The average person will spend six months of their life waiting for red lights to turn green.",
  "The word 'nerd' was first coined by Dr. Seuss in 'If I Ran the Zoo.'",
  "The first known contraceptive was crocodile dung used by Egyptians in 2000 BC.",
  "A group of flamingos is called a 'flamboyance.'",
  "There are more possible iterations of a game of chess than there are atoms in the known universe.",
  "An individual blood cell takes about 60 seconds to make a complete circuit of the body.",
  "Squirrels plant thousands of new trees each year simply by forgetting where they put their acorns.",
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896, lasting only 38 minutes.",
  "Venus is the only planet that rotates clockwise.",
  "A day on Venus is longer than a year on Venus.",
  "The Great Wall of China is visible from space with the naked eye.",
  "Bananas are berries, but strawberries aren't.",
  "A 'jiffy' is an actual unit of time: 1/100th of a second.",
  "Honey never spoils; archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
  "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion.",
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896, lasting only 38 minutes.",
  "Octopuses have three hearts and blue blood.",
  "Cows have best friends and can become stressed when they are separated.",
  "The largest desert in the world is Antarctica.",
  "A 'jiffy' is an actual unit of time: 1/100th of a second.",
  "A group of pugs is called a 'grumble.'",
  "The human brain has a memory capacity equivalent to approximately 2.5 petabytes.",
  "Cows have best friends and can become stressed when they are separated.",
  "A baby spider is called a spiderling.",
  "The world's largest volcano is underwater in Hawaii.",
  "The longest word without a vowel is 'rhythms.'",
  "The average person will spend six months of their life waiting for red lights to turn green.",
  "A day on Venus is longer than a year on Venus.",
  "A 'quokka' is a small herbivorous marsupial that is often referred to as the 'happiest animal on Earth.'",
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896, lasting only 38 minutes.",
  "The longest word in the English language without a vowel is 'rhythms.'",
  "The word 'bookkeeper' (and its variants) is the only unhyphenated English word with three consecutive double letters.",
  "A 'googol' is the number 1 followed by 100 zeros.",
  "Bananas are berries, but strawberries aren't.",
  "Honey never spoils; archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
  "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion.",
  "Octopuses have three hearts and blue blood.",
  "A group of flamingos is called a 'flamboyance.'",
  "A single cloud can weigh more than 1 million pounds.",
  "The shortest war in history was between Britain and Zanzibar in 1896, lasting only 38 minutes.",
  "A single rainforest can produce 20% of the Earth's oxygen.",
  "A 'billion' seconds is about 31.7 years.",
  "The word 'nerd' was first coined by Dr. Seuss in 'If I Ran the Zoo.'",
  "The average person walks the equivalent of three times around the world in a lifetime.",
  "A group of owls is called a 'parliament.'",
  "The longest recorded flight of a chicken is 13 seconds.",
  "The dot over the letter 'i' is called a tittle.",
  "There are more possible iterations of a game of chess than there are atoms in the known universe.",
  "A 'billion' seconds is about 31.7 years.",
  "The longest recorded flight of a chicken is 13 seconds.",
  "The dot over the letter 'i' is called a tittle.",
  "The world's largest desert is Antarctica.",
  "A group of owls is called a 'parliament.'",
  "The longest recorded flight of a chicken is 13 seconds.",
  "The dot over the letter 'i' is called a tittle.",
  "The average person walks the equivalent of three times around the world in a lifetime.",
  "A 'jiffy' is an actual unit of time: 1/100th of a second.",
  "The human brain is more active during sleep than during the day when awake.",
  "A group of jellyfish is called a 'smack.'",
  "A day on Venus is longer than a year on Venus.",
  "The Great Wall of China is not visible from the Moon without aid.",
  "A 'jiffy' is an actual unit of time: 1/100th of a second.",
  "The word 'nerd' was first coined by Dr. Seuss in 'If I Ran the Zoo.'",
  "A snowflake can take up to two hours to fall from the cloud to the ground.",
  "The shortest war in history was between Britain and Zanzibar in 1896, lasting only 38 minutes.",
  "A bolt of lightning is five times hotter than the surface of the sun.",
  "The oldest known vegetable is the pea.",
  "Polar bear skin is black.",
  "A flea can jump 350 times its body length.",
  "The Mona Lisa has no eyebrows.",
  "The average person will spend six months of their life waiting for red lights to turn green.",
  "The word 'nerd' was first coined by Dr. Seuss in 'If I Ran the Zoo.'",
  "The first known contraceptive was crocodile dung used by Egyptians in 2000 BC.",
  "A group of flamingos is called a 'flamboyance.'",
  "There are more possible iterations of a game of chess than there are atoms in the known universe.",
  "An individual blood cell takes about 60 seconds to make a complete circuit of the body.",
  "Squirrels plant thousands of new trees each year simply by forgetting where they put their acorns.",
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896, lasting only 38 minutes.",
  "Venus is the only planet that rotates clockwise.",
  "A day on Venus is longer than a year on Venus.",
  "The Great Wall of China is visible from space with the naked eye.",
  "Bananas are berries, but strawberries aren't.",
  "A 'jiffy' is an actual unit of time: 1/100th of a second.",
  "Honey never spoils; archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
  "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion.",
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896, lasting only 38 minutes.",
  "Octopuses have three hearts and blue blood.",
  "Cows have best friends and can become stressed when they are separated.",
  "The largest desert in the world is Antarctica.",
  "A 'jiffy' is an actual unit of time: 1/100th of a second.",
  "A group of pugs is called a 'grumble.'",
  "The human brain has a memory capacity equivalent to approximately 2.5 petabytes.",
  "Cows have best friends and can become stressed when they are separated.",
  "A baby spider is called a spiderling.",
  "The world's largest volcano is underwater in Hawaii.",
  "The longest word without a vowel is 'rhythms.'",
  "The average person will spend six months of their life waiting for red lights to turn green.",
  "A day on Venus is longer than a year on Venus.",
  "A 'quokka' is a small herbivorous marsupial that is often referred to as the 'happiest animal on Earth.'",
  "The shortest war in history was between Britain and Zanzibar on August 27, 1896, lasting only 38 minutes.",
  "The longest word in the English language without a vowel is 'rhythms.'",
  "The word 'bookkeeper' (and its variants) is the only unhyphenated English word with three consecutive double letters.",
  "A 'googol' is the number 1 followed by 100 zeros.",
  "Bananas are berries, but strawberries aren't.",
  "Honey never spoils; archaeologists have found pots of honey in ancient Egyptian tombs that are over 3,000 years old and still perfectly edible.",
  "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion.",
  "Octopuses have three hearts and blue blood.",
  "A group of flamingos is called a 'flamboyance.'",
  "A single cloud can weigh more than 1 million pounds.",
  "The shortest war in history was between Britain and Zanzibar in 1896, lasting only 38 minutes.",
  "A single rainforest can produce 20% of the Earth's oxygen.",
  "A 'billion' seconds is about 31.7 years.",
];

export default Facts;
