const Riddles = [
  "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. Answer: An echo.",
  "The more you take, the more you leave behind. Answer: Footsteps.",
  "I can fly without wings. I can cry without eyes. Wherever I go, darkness follows me. Answer: A cloud.",
  "I have keys but open no locks. I have space but no room. You can enter, but you can't go inside. Answer: A keyboard.",
  "I can be cracked, made, told, and played. What am I? Answer: A joke.",
  "The more you take, the more you leave behind. What am I? Answer: Footsteps.",
  "What comes once in a minute, twice in a moment, but never in a thousand years? Answer: The letter 'M'.",
  "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. Answer: An echo.",
  "The person who makes it, sells it. The person who buys it never uses it. What is it? Answer: A coffin.",
  "The more you take, the more you leave behind. What am I? Answer: Footsteps.",
  "I can fly without wings. I can cry without eyes. Wherever I go, darkness follows me. Answer: A cloud.",
  "What has a heart that doesn't beat? Answer: An artichoke.",
  "What has a head, a tail, is brown, and has no legs? Answer: A penny.",
  "I'm tall when I'm young, and I'm short when I'm old. What am I? Answer: A candle.",
  "The more you take, the more you leave behind. What am I? Answer: Footsteps.",
  "What has keys but can't open locks? Answer: A piano.",
  "I can be cracked, made, told, and played. What am I? Answer: A joke.",
  "What comes once in a minute, twice in a moment, but never in a thousand years? Answer: The letter 'M'.",
  "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. Answer: An echo.",
  "The person who makes it, sells it. The person who buys it never uses it. What is it? Answer: A coffin.",
  "The more you take, the more you leave behind. What am I? Answer: Footsteps.",
  "I can fly without wings. I can cry without eyes. Wherever I go, darkness follows me. Answer: A cloud.",
  "What has a heart that doesn't beat? Answer: An artichoke.",
  "What has a head, a tail, is brown, and has no legs? Answer: A penny.",
  "I'm tall when I'm young, and I'm short when I'm old. What am I? Answer: A candle.",
  "The more you take, the more you leave behind. What am I? Answer: Footsteps.",
  "What has keys but can't open locks? Answer: A piano.",
  "I can be cracked, made, told, and played. What am I? Answer: A joke.",
  "What comes once in a minute, twice in a moment, but never in a thousand years? Answer: The letter 'M'.",
  "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. Answer: An echo.",
  "The person who makes it, sells it. The person who buys it never uses it. What is it? Answer: A coffin.",
  "The more you take, the more you leave behind. What am I? Answer: Footsteps.",
  "I can fly without wings. I can cry without eyes. Wherever I go, darkness follows me. Answer: A cloud.",
  "What has a heart that doesn't beat? Answer: An artichoke.",
  "What has a head, a tail, is brown, and has no legs? Answer: A penny.",
  "I'm tall when I'm young, and I'm short when I'm old. What am I? Answer: A candle.",
  "The more you take, the more you leave behind. What am I? Answer: Footsteps.",
  "What has keys but can't open locks? Answer: A piano.",
  "I can be cracked, made, told, and played. What am I? Answer: A joke.",
  "What comes once in a minute, twice in a moment, but never in a thousand years? Answer: The letter 'M'.",
  "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. Answer: An echo.",
  "The person who makes it, sells it. The person who buys it never uses it. What is it? Answer: A coffin.",
  "The more you take, the more you leave behind. What am I? Answer: Footsteps.",
  "I can fly without wings. I can cry without eyes. Wherever I go, darkness follows me. Answer: A cloud.",
  "What has a heart that doesn't beat? Answer: An artichoke.",
  "What has a head, a tail, is brown, and has no legs? Answer: A penny.",
  "I'm tall when I'm young, and I'm short when I'm old. What am I? Answer: A candle.",
  "The more you take, the more you leave behind. What am I? Answer: Footsteps.",
  "What has keys but can't open locks? Answer: A piano.",
  "I can be cracked, made, told, and played. What am I? Answer: A joke.",
  "What comes once in a minute, twice in a moment, but never in a thousand years? Answer: The letter 'M'.",
  "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. Answer: An echo.",
  "The person who makes it, sells it. The person who buys it never uses it. What is it? Answer: A coffin.",
  "The more you take, the more you leave behind. What am I? Answer: Footsteps.",
  "I can fly without wings. I can cry without eyes. Wherever I go, darkness follows me. Answer: A cloud.",
  "What has a heart that doesn't beat? Answer: An artichoke.",
  "What has a head, a tail, is brown, and has no legs? Answer: A penny.",
  "I'm tall when I'm young, and I'm short when I'm old. What am I? Answer: A candle.",
  "The more you take, the more you leave behind. Footsteps.",
  "What has keys but can't open locks? A piano.",
  "I can be cracked, made, told, and played. What am I? A joke.",
  "What comes once in a minute, twice in a moment, but never in a thousand years? The letter 'M'.",
  "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. An echo.",
  "The person who makes it, sells it. The person who buys it never uses it. What is it? A coffin.",
  "The more you take, the more you leave behind. Footsteps.",
  "I can fly without wings. I can cry without eyes. Wherever I go, darkness follows me. A cloud.",
  "What has a heart that doesn't beat? An artichoke.",
  "What has a head, a tail, is brown, and has no legs? A penny.",
  "I'm tall when I'm young, and I'm short when I'm old. What am I? A candle.",
  "The more you take, the more you leave behind. Footsteps.",
  "What has keys but can't open locks? A piano.",
  "I can be cracked, made, told, and played. What am I? A joke.",
  "What comes once in a minute, twice in a moment, but never in a thousand years? The letter 'M'.",
  "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. An echo.",
  "The person who makes it, sells it. The person who buys it never uses it. What is it? A coffin.",
  "The more you take, the more you leave behind. Footsteps.",
  "I can fly without wings. I can cry without eyes. Wherever I go, darkness follows me. A cloud.",
  "What has a heart that doesn't beat? An artichoke.",
  "What has a head, a tail, is brown, and has no legs? A penny.",
  "I'm tall when I'm young, and I'm short when I'm old. What am I? A candle.",
  "The more you take, the more you leave behind. Footsteps.",
  "What has keys but can't open locks? A piano.",
  "I can be cracked, made, told, and played. What am I? A joke.",
  "What comes once in a minute, twice in a moment, but never in a thousand years? The letter 'M'.",
  "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. An echo.",
  "The person who makes it, sells it. The person who buys it never uses it. What is it? A coffin.",
  "The more you take, the more you leave behind. Footsteps.",
  "I can fly without wings. I can cry without eyes. Wherever I go, darkness follows me. A cloud.",
  "What has a heart that doesn't beat? An artichoke.",
  "What has a head, a tail, is brown, and has no legs? A penny.",
  "I'm tall when I'm young, and I'm short when I'm old. What am I? A candle.",
  "The more you take, the more you leave behind. Footsteps.",
  "What has keys but can't open locks? A piano.",
  "I can be cracked, made, told, and played. What am I? A joke.",
  "What comes once in a minute, twice in a moment, but never in a thousand years? The letter 'M'.",
  "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. An echo.",
  "The person who makes it, sells it. The person who buys it never uses it. What is it? A coffin.",
  "The more you take, the more you leave behind. Footsteps.",
  "I can fly without wings. I can cry without eyes. Wherever I go, darkness follows me. A cloud.",
  "What has a heart that doesn't beat? An artichoke.",
  "What has a head, a tail, is brown, and has no legs? A penny.",
  "I'm tall when I'm young, and I'm short when I'm old. What am I? A candle.",
  "The more you take, the more you leave behind. Footsteps.",
  "What has keys but can't open locks? A piano.",
  "I can be cracked, made, told, and played. What am I? A joke.",
  "What comes once in a minute, twice in a moment, but never in a thousand years? The letter 'M'.",
  "I speak without a mouth and hear without ears. I have no body, but I come alive with the wind. An echo.",
  "The person who makes it, sells it. The person who buys it never uses it. What is it? A coffin.",
  "The more you take, the more you leave behind. Footsteps.",
  "I can fly without wings. I can cry without eyes. Wherever I go, darkness follows me. A cloud.",
  "What has a heart that doesn't beat? An artichoke.",
  "What has a head, a tail, is brown, and has no legs? A penny.",
  "I'm tall when I'm young, and I'm short when I'm old. What am I? A candle.",
];

export default Riddles;
